###############################################################################
#   @author         :   Trent Stanton
#   @date           :   29/05/2019
#   @package        :   Alarm System
#   @description    :   MQTT Alarm System with Alarm from Xiaomi Gateway when alarm panel is Armed and triggered.
#   @url            :   
###############################################################################
# MQTT Control Panel
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code: !secret alarm_code
    triggered:
      pending_time: 0

###############################################################################
#                               Automations
###############################################################################
automation:
# Trigger alarm while armed away
  - alias: 'Trigger alarm while armed away'
    trigger:
    - platform: state
      entity_id: binary_sensor.fibaro_motion_sensor_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_bedroom
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_backdoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_frontdoor
      to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
  
# Start Alarm on Alarm Trigger via Media Player
  
  - alias: Start Siren on Alarm Trigger
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.home_group
        volume_level: 1.0
    - service: media_player.play_media
      data_template:
        entity_id: media_player.home_group
        media_content_id: !secret alarm_media_url
        media_content_type: audio/mp3
    - service: homeassistant.turn_on
      entity_id: 
      - group.all_lights
      - switch.entry_light
      - switch.entryway_light
      - switch.kitchen_light
      - switch.diningroom_light
    - service: notify.telegram_trent
      data_template:
        title: Intruder Alarm
        message: Alarm has been triggered at home!
        data:
          inline_keyboard:
          - "Disarm:/disarmhome"
# Disarm Callback to surveillance_cameras.yaml
# Stop Alarm via Media Player
  - alias: Stop Siren
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      from: 'triggered'
    action:
    - service: media_player.media_stop
      data_template:
        entity_id: media_player.home_group
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.home_group
        volume_level: 0.4
    - service: homeassistant.turn_off
      entity_id: 
      - group.all_lights
      - switch.entry_light
      - switch.entryway_light
      - switch.kitchen_light
      - switch.diningroom_light