###############################################################################
#   @author         :   Trent Stanton
#   @date           :   1/09/2018
#   @package        :   Google Assistant Control
#   @description    :   Google Assistant for Voice Control of Devices
#   @url            :   
###############################################################################
homeassistant:
  customize:
    script.good_night:
      friendly_name: Good Night
      icon: mdi:sleep

google_assistant:
  project_id: !secret gh_project_id
  expose_by_default: true
  exposed_domains:
    - light
    - scene
    - camera
    - vacuum
  entity_config:
    script.good_night:
      expose: true
    script.turn_on_plex:
      expose: true
      aliases:
        - Plex
        - Plex player
    script.turn_on_ps4:
      expose: true
      aliases:
        - PS4
        - Playstation
        - Playstation 4
    script.turn_on_xboxone:
      expose: true
      aliases:
        - Xbox One
        - Xbox
    switch.air_conditioner:
      expose: true
      aliases:
        - AC
        - Air Con
    fan.bedroom_fan:
      expose: true
      aliases:
        - Bedroom Fan
        - Ceiling Fan
    switch.entry_light:
      name: Entry
      expose: true
      aliases:
        - Entry Light
        - Entry Light
        - Entry Switch
        - Front Light
      room: Entry
    switch.entryway_light:
      name: Entryway
      expose: true
      aliases:
        - Entryway Light
        - Entryway Light
        - Entryway Switch
      room: Entryway
    light.livingroom:
      name: Living Room
      expose: true
      aliases:
        - Living Room Light
        - Living Room Lights
        - Living Room Switch
        - Family Room Light
        - Family Room Switch
      room: Living Room
    switch.living_room_lamp:
      name: Living Room
      expose: true
      aliases:
        - Living Room Lamp
        - Family Room Lamp
      room: Living Room
    switch.kitchen_light:
      name: Kitchen
      expose: true
      aliases:
        - Kitchen Light
        - Kitchen Lights
        - Kitchen Switch
      room: Kitchen
    switch.diningroom_light:
      name: Dining room
      expose: true
      aliases:
        - Dining room Light
        - Dining room Lights
        - Dining room Switch
      room: Kitchen
    light.trent_bedside:
      name: Trent Bedside
      expose: true
      aliases:
        - Trent Bedside Light
        - Trents Bedside Light
        - Trent Bedside Lamp
        - Trents Bedside Lamp
        - Trent Lamp
        - Trents Lamp
        - Trent Bedside Switch
        - Trents Bedside Switch
      room: Bedroom
    light.rachel_bedside:
      name: Rachel Bedside
      expose: true
      aliases:
        - Rachel Bedside Light
        - Rachels Bedside Light
        - Rachel Bedside Lamp
        - Rachels Bedside Lamp
        - Rachel Lamp
        - Rachels Lamp
        - Rachel Bedside Switch
        - Rachels Bedside Switch
      room: Bedroom
    light.study_desk_lamp:
      name: Study Desk Lamp
      expose: true
      aliases:
        - Study Desk Light
        - Office Desk Light
        - Study Desk Lamp
        - Office Desk Lamp
        - Study Lamp
        - Office Lamp
        - Study Light
        - Office Light
      room: Study
    switch.outside_heater:
      name: Outside Heater
      expose: true
      aliases:
        - Outside Heating
        - Outdoor Heater
        - Outdoor Heating
        - Deck Heater
        - Deck Heating
        - Decking Heater
        - Decking Heating
      room: Outside
    switch.plug_washingmachine:
      expose: true
    switch.projector_power:
      expose: true
    switch.reciever_power:
      expose: true
    media_player.living_room_tv:
      expose: true
      aliases:
        - Living Room TV
        - LG TV
        - Lounge Room TV
      room: Living Room
    binary_sensor.door_frontdoor:
      expose: true
      room: Entry
    binary_sensor.door_backdoor:
      expose: true
      room: Living Room
    binary_sensor.window_bedroom:
      expose: true
      room: Bedroom
    binary_sensor.window_projectorroom:
      expose: true
      room: Projector Room
    binary_sensor.window_livingroom1:
      expose: true
      room: Living Room
    binary_sensor.window_livingroom2:
      expose: true
      room: Living Room
    binary_sensor.window_livingroom3:
      expose: true
      room: Living Room
    binary_sensor.window_diningroom1:
      expose: true
      room: Dining Room
    binary_sensor.window_diningroom2:
      expose: true
      room: Dining Room