###############################################################################
#   @author         :   Trent Stanton
#   @date           :   18/05/2019
#   @package        :   
#   @description    :   Dimming of Living Room light when media is playing
#   @url            :   
###############################################################################
input_boolean:
  mediaplayer_dimmer_livingroom:
    name: Dim Lights
  plex_dimmer_livingroom:
    name: Dim Lights with Plex
  plex_status:
    name: Plex Status

input_number:
  mediaplayer_dimmer_livingroom:
    name: '% Level'
    min: 0
    max: 75
    step: 5
    mode: slider

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: Plex Webhook MQTT ## https://HAURL/api/webhook/secretwebhookid ##
    trigger:
      - platform: webhook
        webhook_id: !secret plex_webhook
    action:
     - service: mqtt.publish
       data_template:
         topic: 'plex/update'
         payload_template: >
           {{ (trigger.data['payload'] | string)[12:][:-2] | replace ("\\\\", "\\") | replace ("\\\'", "'") | replace ("\\x","?") }}
  - alias: Plex State Toggle
    trigger:
      platform: mqtt
      topic: 'plex/update'
    condition:
      condition: and
      conditions:
      - condition: template
        value_template: !secret plex_account_trigger
      - condition: template
        value_template: !secret plex_livingroom_trigger
    action:
      service_template: >
          {% if ((trigger.payload_json.event == 'media.play') or (trigger.payload_json.event == 'media.resume')) %}
            input_boolean.turn_on
          {% elif ((trigger.payload_json.event == 'media.pause') or (trigger.payload_json.event == 'media.stop')) %}
            input_boolean.turn_off
          {% endif %}
      entity_id: input_boolean.plex_status
  - alias: "Living Room TV Plex - Playing"
    trigger:
    - platform: state
      entity_id: input_boolean.plex_status
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: input_boolean.mediaplayer_dimmer_livingroom
        state: 'on'
      - condition: state
        entity_id: light.livingroom
        state: 'on'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.livingroom
        brightness_pct: '{{ states.input_number.mediaplayer_dimmer_livingroom.state | int }}'
  - alias: "Living Room TV Plex - Paused / Stopped"
    trigger:
    - platform: state
      entity_id: input_boolean.plex_status
      to: 'off'
    condition:
      condition: and
      conditions:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: input_boolean.mediaplayer_dimmer_livingroom
        state: 'on'
      - condition: state
        entity_id: light.livingroom
        state: 'on'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.livingroom
        brightness_pct: '100'

# Living Room TV Media Player - Old Method, Too Slow.

#  - alias: "Living Room TV - Playing"
#    trigger:
#    - platform: state
#      entity_id: media_player.living_room_tv
#      to: 'playing'
#    condition:
#      condition: and
#      conditions:
#  #    - condition: sun
#  #      after: sunset
#      - condition: state
#        entity_id: input_boolean.mediaplayer_dimmer_livingroom
#        state: 'on'
#      - condition: state
#        entity_id: light.livingroom
#        state: 'on'
#    action:
#    - service: light.turn_on
#      data_template:
#        entity_id: light.livingroom
#        brightness_pct: '{{ states.input_number.mediaplayer_dimmer_livingroom.state | int }}'
#  - alias: "Living Room TV - Paused"
#    trigger:
#    - platform: state
#      entity_id: media_player.living_room_tv
#      to: 'paused'
#    condition:
#      condition: and
#      conditions:
#  #    - condition: sun
#  #      after: sunset
#      - condition: state
#        entity_id: input_boolean.mediaplayer_dimmer_livingroom
#        state: 'on'
#      - condition: state
#        entity_id: light.livingroom
#        state: 'on'
#    action:
#    - service: light.turn_on
#      data_template:
#        entity_id: light.livingroom
#        brightness_pct: '100'
#  - alias: "Living Room TV - Stopped"
#    trigger:
#    - platform: state
#      entity_id: media_player.living_room_tv
#      from: 'playing'
#      to: 'idle'
#    - platform: state
#      entity_id: media_player.living_room_tv
#      from: 'paused'
#      to: 'idle'
#    - platform: state
#      entity_id: media_player.living_room_tv
#      from: 'paused'
#      to: 'off'
#    - platform: state
#      entity_id: media_player.living_room_tv
#      from: 'paused'
#      to: 'off'
#    condition:
#      condition: and
#      conditions:
#  #    - condition: sun
#  #      after: sunset
#      - condition: state
#        entity_id: input_boolean.mediaplayer_dimmer_livingroom
#        state: 'on'
#      - condition: state
#        entity_id: light.livingroom
#        state: 'on'
#    action:
#    - service: scene.turn_on
#      entity_id: scene.living_room_light_full